import React, { useState, useMemo } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { 
  Search, 
  ChevronRight, 
  CreditCard, 
  FileText, 
  Users, 
  Terminal, 
  Copy, 
  Check, 
  Layout, 
  Filter, 
  Bell, 
  BookOpen,
  MessageSquare,
  Server
} from "lucide-react";

// ==========================================
// 1. STYLES & THEME
// ==========================================
const ConsoleStyles = () => (
  <style>{`
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap');
    
    :root {
      --obsidian: #0f172a;
      --industrial-orange: #f97316; 
      --canvas: #f1f5f9;
    }

    body { 
      font-family: 'Inter', sans-serif; 
      background-color: var(--canvas); 
      color: #334155; 
      font-size: 14px; /* Reduced from 15px */
    }

    .font-mono { font-family: 'JetBrains Mono', monospace; }

    .scroll-panel::-webkit-scrollbar { width: 8px; }
    .scroll-panel::-webkit-scrollbar-track { background: transparent; }
    .scroll-panel::-webkit-scrollbar-thumb { background: #cbd5e1; border-radius: 4px; }
    .scroll-panel::-webkit-scrollbar-thumb:hover { background: #94a3b8; }

    .code-window {
        background: #0f172a;
        color: #e2e8f0;
        border-radius: 8px;
        font-family: 'JetBrains Mono', monospace;
        font-size: 12px; /* Reduced from 13px */
        border: 1px solid #334155;
        box-shadow: inset 0 2px 4px 0 rgba(0, 0, 0, 0.3);
    }

    /* Hover Animations */
    .nav-item-hover { position: relative; overflow: hidden; }
    .nav-item-hover::before {
        content: ''; position: absolute; left: 0; top: 0; height: 100%; width: 4px;
        background-color: var(--industrial-orange); transform: scaleY(0); transition: transform 0.2s ease;
    }
    .nav-item-hover:hover::before { transform: scaleY(1); }

    .table-row-hover { transition: all 0.15s ease-in-out; border-left: 4px solid transparent; }
    .table-row-hover:hover {
        background-color: #f8fafc; border-left-color: var(--industrial-orange); transform: translateX(2px);
    }
  `}</style>
);

// ==========================================
// 2. DATA
// ==========================================

const CATEGORIES = [
    { id: "All", label: "All Topics", icon: Layout },
    { id: "Billing", label: "Billing & Finance", icon: CreditCard },
    { id: "Leases", label: "Lease Management", icon: FileText },
    { id: "Tenants", label: "Tenant Portal", icon: Users },
    { id: "API", label: "API Integration", icon: Terminal },
    { id: "System", label: "System Config", icon: Server },
];

const RAW_FAQS = [
    {
        id: "FAQ-101", category: "Billing", views: "1.2k", updated: "2 days ago",
        question: "How do I handle M-Pesa STK Push timeouts?",
        preview: "Steps to take when a customer does not receive the prompt.",
        content: { 
            answer: "If the STK push times out (approx 10s), do not immediately retry. First, verify the phone number format (must be 254...). If valid, check the transaction log. If the status is 'Failed', you may manually trigger a retry via the API.", 
            code: "POST /api/v1/payments/retry \n{\n  \"transaction_id\": \"TX123\",\n  \"reason\": \"timeout\"\n}" 
        }
    },
    {
        id: "FAQ-102", category: "Leases", views: "850", updated: "1 week ago",
        question: "Digital Signature Validity",
        preview: "Are the generated PDF signatures legally binding?",
        content: { 
            answer: "Yes. All leases generated by the platform adhere to the Kenya Information and Communications Act. The digital signature includes a timestamp and a unique hash that verifies the document integrity.", 
            code: "// Verification Logic\nverifySignature(docHash, certificate);" 
        }
    },
    {
        id: "FAQ-103", category: "API", views: "2.4k", updated: "3 days ago",
        question: "Rate Limiting on Public Endpoints",
        preview: "Understanding 429 errors and headers.",
        content: { 
            answer: "The public API is rate-limited to 60 requests per minute. Look for the 'Retry-After' header in the 429 response to know when to send the next request.", 
            code: "HTTP/1.1 429 Too Many Requests\nRetry-After: 30" 
        }
    },
    {
        id: "FAQ-104", category: "Tenants", views: "500", updated: "1 month ago",
        question: "Resetting Tenant Portal Passwords",
        preview: "Admin override for tenant credentials.",
        content: { 
            answer: "Admins cannot see tenant passwords. You can only trigger a password reset email. Go to Tenant Directory > Select Tenant > Actions > Send Reset Link.", 
            code: null 
        }
    },
    {
        id: "FAQ-105", category: "Billing", views: "3.1k", updated: "5 hours ago",
        question: "Reversing a Duplicate Payment",
        preview: "How to process refunds for double charges.",
        content: { 
            answer: "Navigate to Finance > Transactions. Locate the duplicate ID. Click 'Reverse'. Note: M-Pesa reversals take up to 72 hours to reflect in the customer's wallet.", 
            code: null 
        }
    },
    {
        id: "FAQ-106", category: "System", views: "120", updated: "2 weeks ago",
        question: "Setting up Custom Domains",
        preview: "Pointing your domain to our servers.",
        content: { 
            answer: "Create a CNAME record in your DNS provider settings pointing to 'custom.helphub.io'. SSL certificates are provisioned automatically within 24 hours.", 
            code: "Type: CNAME\nName: portal\nValue: custom.helphub.io" 
        }
    },
    {
        id: "FAQ-107", category: "API", views: "200", updated: "4 days ago",
        question: "Webhook Signatures",
        preview: "Verifying the authenticity of incoming webhooks.",
        content: {
            answer: "All webhooks include an 'X-Hub-Signature' header. Calculate the HMAC SHA256 of the payload using your secret key and compare it to the header.",
            code: "const hmac = crypto.createHmac('sha256', secret);\nconst digest = hmac.update(payload).digest('hex');"
        }
    }
];

// ==========================================
// 3. SUB-COMPONENTS
// ==========================================

const TagBadge = ({ label }) => {
    const styles = {
        "Billing": "bg-blue-50 text-blue-600 border-blue-100",
        "Leases": "bg-purple-50 text-purple-600 border-purple-100",
        "API": "bg-slate-100 text-slate-600 border-slate-200",
        "Tenants": "bg-orange-50 text-orange-600 border-orange-100",
        "System": "bg-emerald-50 text-emerald-600 border-emerald-100",
    };
    return (
        <span className={`px-2.5 py-1 rounded-md text-xs font-bold uppercase tracking-wider border ${styles[label] || "bg-gray-50 text-gray-600"}`}>
            {label}
        </span>
    );
};

const ExpandedPanel = ({ item }) => {
    return (
        <div className="bg-slate-50 border-t border-b border-slate-200 p-6 pl-14 shadow-inner">
            <div className="bg-white border border-slate-200 rounded-lg overflow-hidden shadow-sm">
                <div className="flex border-b border-slate-100 bg-slate-50/50 px-5 py-3">
                    <span className="text-xs font-bold text-slate-500 uppercase tracking-wide">Official Answer</span>
                </div>
                <div className="p-6 flex flex-col md:flex-row gap-8">
                    <div className="flex-1">
                        {/* Reduced from text-base to text-sm */}
                        <p className="text-sm text-slate-700 leading-relaxed mb-5">
                            {item.content.answer}
                        </p>
                        <div className="flex gap-3 mt-5">
                            <button className="flex items-center gap-2 text-xs font-bold border border-slate-200 text-slate-600 px-4 py-2 rounded hover:bg-slate-50 hover:text-orange-600 transition-colors">
                                <Check className="w-4 h-4" /> Mark as Helpful
                            </button>
                            <button className="flex items-center gap-2 text-xs font-bold border border-slate-200 text-slate-600 px-4 py-2 rounded hover:bg-slate-50 hover:text-blue-600 transition-colors">
                                <Copy className="w-4 h-4" /> Copy Link
                            </button>
                        </div>
                    </div>
                    {item.content.code && (
                        <div className="flex-1 md:max-w-md">
                            <div className="code-window p-4 relative group">
                                <div className="absolute top-3 right-3 opacity-50 text-xs text-slate-400">SNIPPET</div>
                                <pre className="overflow-x-auto text-slate-300 pt-2">{item.content.code}</pre>
                            </div>
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
};

// ==========================================
// 4. MAIN PAGE
// ==========================================

export default function FAQConsole() {
    const [activeCat, setActiveCat] = useState("All");
    const [expandedId, setExpandedId] = useState(null);

    // Filter Logic
    const filteredData = useMemo(() => {
        if (activeCat === "All") return RAW_FAQS;
        return RAW_FAQS.filter(item => item.category === activeCat);
    }, [activeCat]);

    const handleCatClick = (id) => {
        setActiveCat(id);
        setExpandedId(null); 
    };

    return (
        <>
        <ConsoleStyles />
        <div className="flex h-screen bg-[#0f172a] overflow-hidden">
            
            {/* --- SIDEBAR --- */}
            <aside className="w-72 bg-[#0f172a] border-r border-slate-800 flex flex-col z-20 shadow-xl">
                {/* Branding */}
                <div className="h-20 flex items-center px-6 border-b border-slate-800">
                    <div className="w-8 h-8 bg-gradient-to-br from-orange-500 to-red-500 rounded-md flex items-center justify-center text-white shadow-lg mr-3">
                        <BookOpen className="w-5 h-5" />
                    </div>
                    <div>
                        {/* Reduced from text-base to text-sm */}
                        <h1 className="font-bold text-slate-100 text-sm tracking-tight">HelpHub</h1>
                        <p className="text-xs text-slate-500 font-mono uppercase">Knowledge Console</p>
                    </div>
                </div>

                {/* Nav */}
                <div className="p-4 flex-1 overflow-y-auto">
                    <div className="mb-8">
                        <p className="px-4 text-xs font-bold text-slate-500 uppercase tracking-widest mb-3">Modules</p>
                        <nav className="space-y-1.5">
                            {CATEGORIES.map((cat) => {
                                const isActive = activeCat === cat.id;
                                const count = cat.id === "All" ? RAW_FAQS.length : RAW_FAQS.filter(i => i.category === cat.id).length;
                                
                                return (
                                    <button 
                                        key={cat.id} 
                                        onClick={() => handleCatClick(cat.id)}
                                        className={`w-full nav-item-hover flex items-center justify-between px-4 py-3 rounded-md text-sm font-medium transition-all duration-200 group
                                        ${isActive ? 'bg-slate-800/50 text-white' : 'text-slate-400 hover:bg-slate-800/50 hover:text-slate-200'}`}
                                    >
                                        <div className="flex items-center gap-3">
                                            <cat.icon className={`w-5 h-5 transition-colors ${isActive ? 'text-orange-500' : 'text-slate-500 group-hover:text-orange-400'}`} />
                                            {cat.label}
                                        </div>
                                        <span className={`text-xs px-2 py-0.5 rounded-full ${isActive ? 'bg-orange-500 text-white' : 'bg-slate-700 text-slate-300'}`}>
                                            {count}
                                        </span>
                                    </button>
                                );
                            })}
                        </nav>
                    </div>
                </div>

                <div className="p-5 border-t border-slate-800 bg-[#0b1120]">
                    <button className="w-full flex items-center justify-center gap-2 py-2.5 rounded border border-slate-700 text-sm text-slate-300 hover:bg-slate-800 hover:text-white transition-colors">
                        <MessageSquare className="w-4 h-4" /> Contact Support
                    </button>
                </div>
            </aside>

            {/* --- MAIN CONTENT --- */}
            <main className="flex-1 flex flex-col min-w-0 bg-[#f1f5f9] relative">
                
                {/* Header Toolbar */}
                <header className="h-20 bg-white border-b border-slate-200 flex items-center justify-between px-8 shadow-sm z-10">
                    <div className="flex items-center gap-3">
                        <div className="flex items-center gap-2 px-4 py-1.5 bg-slate-100 rounded text-sm font-bold text-slate-700">
                             <Filter className="w-4 h-4 text-slate-400" />
                             Current View: <span className="text-orange-600">{CATEGORIES.find(c => c.id === activeCat)?.label}</span>
                        </div>
                    </div>

                    {/* Search */}
                    <div className="flex items-center gap-6">
                        <div className="relative group">
                            <Search className="absolute left-3.5 top-3 w-5 h-5 text-slate-400 group-hover:text-blue-500 transition-colors" />
                            <input 
                                type="text" 
                                placeholder="Search repository..." 
                                className="pl-10 pr-4 py-2.5 w-72 bg-slate-50 border border-slate-200 rounded-lg text-sm font-medium text-slate-700 placeholder-slate-400 outline-none focus:ring-2 focus:ring-blue-100 focus:border-blue-400 transition-all"
                            />
                        </div>
                        <div className="h-8 w-px bg-slate-200"></div>
                        <button className="relative p-2.5 text-slate-500 hover:bg-slate-100 rounded-full transition-colors">
                            <Bell className="w-5 h-5" />
                        </button>
                    </div>
                </header>

                {/* Content Body */}
                <div className="flex-1 overflow-y-auto p-8 scroll-panel">
                    
                    {/* Main Table */}
                    <div className="bg-white border border-slate-200 rounded-lg shadow-sm overflow-hidden mt-2">
                        {/* Table Head */}
                        <div className="grid grid-cols-12 gap-6 px-6 py-4 bg-slate-50/80 border-b border-slate-200 text-xs font-bold text-slate-500 uppercase tracking-wider backdrop-blur-sm sticky top-0">
                            <div className="col-span-2">Reference ID</div>
                            <div className="col-span-5">Question</div>
                            <div className="col-span-2">Category</div>
                            <div className="col-span-2">Popularity</div>
                            <div className="col-span-1 text-right">Updated</div>
                        </div>

                        {/* Table Body */}
                        <div className="divide-y divide-slate-100 bg-white">
                            {filteredData.length > 0 ? (
                                filteredData.map((faq) => {
                                    const isOpen = expandedId === faq.id;
                                    return (
                                        <div key={faq.id} className="group">
                                            <div 
                                                onClick={() => setExpandedId(isOpen ? null : faq.id)}
                                                className={`table-row-hover grid grid-cols-12 gap-6 px-6 py-4 items-center cursor-pointer 
                                                ${isOpen ? 'bg-blue-50/30 border-l-orange-500' : 'bg-white hover:bg-slate-50'}`}
                                            >
                                                <div className="col-span-2 text-sm font-mono font-medium text-slate-500 group-hover:text-slate-800">
                                                    {faq.id}
                                                </div>
                                                <div className="col-span-5">
                                                    {/* Reduced from text-base to text-sm */}
                                                    <div className={`text-sm font-semibold transition-colors ${isOpen ? 'text-blue-600' : 'text-slate-800'}`}>
                                                        {faq.question}
                                                    </div>
                                                    <div className="text-xs text-slate-500 truncate mt-1">{faq.preview}</div>
                                                </div>
                                                <div className="col-span-2">
                                                    <TagBadge label={faq.category} />
                                                </div>
                                                <div className="col-span-2">
                                                    <div className="flex items-center gap-2">
                                                        <div className="h-2 w-full bg-slate-100 rounded-full overflow-hidden max-w-[100px]">
                                                            <div className="h-full bg-slate-300" style={{ width: '70%' }}></div>
                                                        </div>
                                                        <span className="text-xs text-slate-400">{faq.views}</span>
                                                    </div>
                                                </div>
                                                <div className="col-span-1 text-right text-xs font-mono text-slate-400">
                                                    {faq.updated}
                                                </div>
                                            </div>
                                            
                                            <AnimatePresence>
                                                {isOpen && (
                                                    <motion.div
                                                        initial={{ height: 0, opacity: 0 }}
                                                        animate={{ height: "auto", opacity: 1 }}
                                                        exit={{ height: 0, opacity: 0 }}
                                                        transition={{ duration: 0.2 }}
                                                    >
                                                        <ExpandedPanel item={faq} />
                                                    </motion.div>
                                                )}
                                            </AnimatePresence>
                                        </div>
                                    );
                                })
                            ) : (
                                <div className="p-14 text-center">
                                    <div className="w-14 h-14 bg-slate-50 rounded-full flex items-center justify-center mx-auto mb-4">
                                        <Search className="w-7 h-7 text-slate-300" />
                                    </div>
                                    <h3 className="text-base font-bold text-slate-700">No results in this category</h3>
                                    <p className="text-sm text-slate-400 mt-1">Try switching back to "All Topics"</p>
                                </div>
                            )}
                        </div>
                        
                        {/* Table Footer */}
                        <div className="px-6 py-4 bg-slate-50 border-t border-slate-200 flex items-center justify-between">
                            <span className="text-xs font-medium text-slate-500">
                                Showing {filteredData.length} records
                            </span>
                            <div className="flex gap-2">
                                <button className="p-1.5 rounded hover:bg-white hover:shadow-sm border border-transparent hover:border-slate-200 transition-all disabled:opacity-50">
                                    <ChevronRight className="w-5 h-5 text-slate-400 rotate-180" />
                                </button>
                                <button className="p-1.5 rounded hover:bg-white hover:shadow-sm border border-transparent hover:border-slate-200 transition-all">
                                    <ChevronRight className="w-5 h-5 text-slate-400" />
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>
        </>
    );
}